### ISSUE TITLE
Extract to set target directory

### ISSUE THREAD

**Issue by pogzie** [some-things/bunk#1]
Hope next release can accommodate setting the path than ~/Documents

**Comment by some-things** [comment]
Thanks for submitting the issue, Pogz! 

This should currently be possible by setting `BUNK_TICKETS_DIR` env var:
https://github.com/some-things/bunk/blob/master/cmd/bunk/cmd/extract.go#L53-L56

Let me know if it meets your needs or if I can change it up a bit to better align with what you're looking for.
